services:
  security-toolbox:
    build:
      context: .
    container_name: security-toolbox
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PYTHONUNBUFFERED=1
    privileged: true
    restart: unless-stopped

  zap:
    image: owasp/zap2docker-weekly
    container_name: zap
    ports:
      - "8080:8080"
    volumes:
      - ./results:/zap/wrk
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: security-api
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
    restart: unless-stopped
