version: '3.8'

services:
  security-toolbox:
    build: .
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISPLAY=:0
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    command: python security_toolbox.py

networks:
  security-network:
    driver: bridge 
